services:
  itau-tracker:
    build:
      context: ./tracker
      dockerfile: Dockerfile
    container_name: itau-tracker
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  itau-tracker-ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: itau-tracker-ui
    ports:
      - 8085:8085
    volumes:
      - ./data:/app/data
      - ./tracker/fetch.py:/app/fetch.py
    env_file:
      - .env
    restart: unless-stopped
