include:
  - monitoring/docker-compose.yml
  - homepage/docker-compose.yml
  - fitbit-exporter/docker-compose.yml
  - news/freshrss/docker-compose.yml
  - news/wallabag/docker-compose.yml
  - news/news-filter/docker-compose.yml
  - finance/itau-tracker/docker-compose.yml
  - caddy/docker-compose.yml

networks:
  default:
    name: pi-services
