{
 "title": "Pi-hole v6",
 "description": "Pi-hole v6 dashboard using amonacoos/pihole6_exporter",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "🥧🕳️ Pi-hole", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Domains being blocked",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pihole_domains_being_blocked" }
   ]
  },
  {
   "title": "Replies by type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_query_replies", "legendFormat": "{{ type }}" }
   ]
  },
  {
   "title": "DNS queries all of types",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "pihole_query_count", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "title": "% ads blocked",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pihole_query_by_status{query_status=\"GRAVITY\"} / on(instance, job) pihole_query_count{category=\"total\"} * 100"
    }
   ]
  },
  {
   "title": "Ads blocked (today)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pihole_query_by_status{query_status=\"GRAVITY\"}",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Queries cached/forwarded",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pihole_query_by_status{query_status=\"CACHE\"}",
     "legendFormat": "Queries cached"
    },
    {
     "expr": "pihole_query_by_status{query_status=\"FORWARDED\"}",
     "legendFormat": "Queries forwarded"
    }
   ]
  },
  {
   "title": "DNS Query types",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "pihole_query_by_type", "legendFormat": "{{ type }}" }
   ]
  },
  {
   "title": "% of ads blocked",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "pihole_query_by_status{query_status=\"GRAVITY\"} / on(instance, job) pihole_query_count{category=\"total\"} * 100",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Forward destinations",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "pihole_query_upstream_count", "legendFormat": "{{ destination }}" }
   ]
  },
  {
   "title": "Unique clients",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "pihole_client_count", "legendFormat": "{{ hostname }}" }
   ]
  }
 ]
}