services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=homepage.pi,${PI_IP}:3001
    volumes:
      - ./config:/app/config
    restart: unless-stopped

networks:
  default:
    name: pi-services
    external: true
