services:
  wallabag:
    image: wallabag/wallabag
    container_name: wallabag
    volumes:
      - wallabag-data:/var/www/wallabag/data
    environment:
      - SYMFONY__ENV__DOMAIN_NAME=http://wallabag.pi
    restart: unless-stopped
volumes:
  wallabag-data:

networks:
  default:
    name: pi-services
    external: true
